---
- name: Open a program on Windows
  hosts: winhost
  gather_facts: no
  collections:
    - community.windows
  tasks:
    - name: Launch Notepad
      win_shell:
        cmd: echo "Hello from Ansible" > C:\Temp\hello.txt
